language: python

python:
  - "2.7"

cache:
  apt: true
  directories:
    - $HOME/miniconda

before_install:
  # install miniconda for Python dependencies
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda -f
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  - conda config --add channels conda-forge
  - conda config --add channels defaults
  - conda config --add channels r
  - conda config --add channels bioconda
  - conda info -a

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip sqlalchemy pyyaml networkx numpy scipy pysam htseq biopython bcbiogff pybedtools bedtools biofluff gimmemotifs=0.10.0=py27_0 rpy2 r-changepoint maxentscan pytest
  - pip install .
#  - pip install nose coverage
#  - pip install coveralls
# # command to run tests, e.g. python setup.py test
script:  
  - python setup.py test
 
#after_sucess:
#  coveralls
