name: pita
channels:
- bioconda
- r
- defaults
- conda-forge
dependencies:
- biofluff
- biopython
- gimmemotifs=0.10.0=py27_0
- bcbiogff
- pysam
- pyyaml
- networkx
- htseq
- sqlalchemy
- pytest
- maxentscan
- rpy2
- r-changepoint
